[datadog_agents]
server1 ansible_host=3.110.159.124  # Change this with Public IP of your instance
server2 ansible_host=13.234.225.225 # Change this with Public IP of your instance
server3 ansible_host=13.233.4.158   # Change this with Public IP of your instance
